TOPLEVEL = Ice40up5kbevnNoXip
ROOT = ../../..
VERILOG = $(ROOT)/hardware/netlist/${TOPLEVEL}.v
BINARY  = $(ROOT)/hardware/netlist/Ice40up5kbevnNoXip.v_toplevel_system_cpu_cpu_RegFilePlugin_regFile.bin
DEVICE = up5k
PACKAGE = sg48
PCF = mapping.pcf
CONSTRAINT = constraint.py

include ../flow/icestorm.mk

