TOPLEVEL = Ice40Hx8kBreakoutLinux
ROOT = ../../..
VERILOG = $(ROOT)/hardware/netlist/${TOPLEVEL}.v
BINARY = $(ROOT)/hardware/netlist/Ice40Hx8kBreakoutLinux.v_toplevel_system_cpu_cpu_RegFilePlugin_regFile.bin
PCF =
DEVICE = hx8k
PACKAGE = ct256

include ../flow/icestorm.mk

